spring:
  application:
    name: healflow-api

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: ${DATABASE_DATASOURCE}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

    jakarta:
      persistence:
        schema-generation:
          scripts:
            action: create
            create-target: create.sql
            create-source: metadata

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI:http://192.168.1.139:3000/api/auth/jwks}

  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  show-actuator: true

server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never

scalar:
  url: ${API_DOCS_URL:http://localhost:8080/v3/api-docs}
  path: /docs
  enabled: true

api:
  prefix: /api
  version: v1
  allowedOrigins: ${FRONTEND_URL}
  key: ${API_SERVICE_KEY}
  key-header: X-API-KEY
  key-path: /user-provisions/**,/specialists/**

medicines-api-url: ${https://medicines-api-production.up.railway.app/api-docs/json}

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: DEBUG
